project_name: 'bart-qa'

model: 'facebook/bart-base'
load_in_8bit: false
device: 'cuda'

dataset: 'wiki_qa'
input_column: 'question'
target_column: 'answer'
drop_columns: ['label', 'question_id', 'document_title']


training:
  batch_size: 32
  warmup_steps: 1000
  num_train_epochs: 1
  lr: 2e-5


evaluation:
  batch_size: 32

logging:
  steps: 100
  report_to: 'wandb'

generation:
  max_length: 32


save_limit: 2
metric_for_best_model: 'rouge2'
seed: 42